version: '3.6'
services:
  api:
    image: membership_management:local
    build:
      dockerfile: Dockerfile
      context: .
    command: bin/dj-run.sh
    volumes:
      - .:/app
    links:
      - db
    ports:
      - 8000:8000
    environment:
      DJANGO_ENV: dev
      ADMIN_ENABLED: 'true'
      DATABASE_NAME: membership_management
      DATABASE_USER: membership_management
      DATABASE_PASSWORD: membership_management
      DATABASE_HOST: db
      DATABASE_ENGINE: django.db.backends.postgresql
      DATABASE_MIGRATE: 'true'
      GENERATE_SAMPLE_DATA: 'true'

  db:
    image: postgres:9.6
    ports:
      - 5433:5432
    volumes:
      - ../data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: membership_management
      POSTGRES_PASSWORD: membership_management
      POSTGRES_DB: membership_management
