# Generated by Django 3.0.4 on 2020-06-11 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200611_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[('SHOPPING', 0), ('WAITING', 1), ('IN_PROGRESS', 2), ('SHIPPING', 3), ('PAID', 4), ('CANCELED', 5)], default=1),
        ),
    ]
