# Generated by Django 3.0.4 on 2020-06-12 08:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('orders', '0004_auto_20200611_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.AddressBook', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[('SHOPPING', 0), ('WAITING', 1), ('IN_PROGRESS', 2), ('SHIPPING', 3), ('PAID', 4), ('CANCELED', 5)], default=0),
        ),
    ]
