# Generated by Django 3.0.4 on 2020-07-01 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20200701_0841'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='burning_point',
            field=models.IntegerField(default=0),
        ),
    ]
