# Generated by Django 3.0.4 on 2020-07-01 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_burning_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='num_of_items',
            field=models.IntegerField(default=0),
        ),
    ]
