# Generated by Django 3.0.4 on 2020-07-02 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20200702_0209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_pay_amount',
        ),
    ]
